In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
!pip install tensorflow

  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     -------------------------------------- 60.8/60.8 kB 648.8 kB/s eta 0:00:00
  Using cached namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
     ---------------------------------------- 0.0/49.8 kB ? eta -:--:--
     ------------------------ --------------- 30.7/49.8 kB 1.3 MB/s eta 0:00:01
     ------------------------ --------------- 30.7/49.8 kB 1.3 MB/s eta 


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
sent[3]

'I am a good boy'

In [19]:
#define the vocabulary size
voc_size = 1000

In [8]:
#one hot represnetation
one_hot_repr = [one_hot(words,vec_size) for words in sent]
one_hot_repr

[[179, 796, 250, 365],
 [179, 796, 250, 160],
 [179, 802, 250, 577],
 [607, 61, 849, 773, 165],
 [607, 61, 849, 773, 284],
 [968, 179, 819, 250, 736],
 [398, 535, 690, 773]]

In [9]:
#word embedding represenatation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 179 796 250 365]
 [  0   0   0   0 179 796 250 160]
 [  0   0   0   0 179 802 250 577]
 [  0   0   0 607  61 849 773 165]
 [  0   0   0 607  61 849 773 284]
 [  0   0   0 968 179 819 250 736]
 [  0   0   0   0 398 535 690 773]]


In [14]:
## feature representation
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\sande\Desktop\Genai\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [25]:
embedded_docs[0]

array([  0,   0,   0,   0, 179, 796, 250, 365], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])
#all the above 10 words of first sentence is converted into 10 dimensions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[ 0.03012364, -0.00582946, -0.03862486,  0.03450272,  0.00155882,
         0.0449743 ,  0.04548038, -0.03343519, -0.00262295,  0.02136638],
       [ 0.03012364, -0.00582946, -0.03862486,  0.03450272,  0.00155882,
         0.0449743 ,  0.04548038, -0.03343519, -0.00262295,  0.02136638],
       [ 0.03012364, -0.00582946, -0.03862486,  0.03450272,  0.00155882,
         0.0449743 ,  0.04548038, -0.03343519, -0.00262295,  0.02136638],
       [ 0.03012364, -0.00582946, -0.03862486,  0.03450272,  0.00155882,
         0.0449743 ,  0.04548038, -0.03343519, -0.00262295,  0.02136638],
       [ 0.03720096, -0.02852336,  0.00746987,  0.02852659,  0.01906009,
         0.04712132, -0.0028413 ,  0.01059198, -0.00691311, -0.01592207],
       [ 0.01556468,  0.00718565,  0.01397724, -0.03121755,  0.02338982,
        -0.01239481,  0.03896124, -0.04721424,  0.0295166 ,  0.02074729],
       [ 0.03931725, -0.02691936,  0.02920808, -0.01436958, -0.00026008,
         0.02650588, -0.03862898, -0.03637772